file = open("Table.csv", "w")
file.write("Name, Age, City\n")
file.write("Suyash, 20, New York\n")
file.write("Tanuj, 21, Los Angeles\n")
file.close()

file = open("Table.csv", "r")
content = file.read()
print(content)
file.close()